server:
  port: 8084

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**
        - id: accommodation-catalog-service
          uri: lb://ACCOMMODATION-CATALOG-SERVICE
          predicates:
            - Path=/api/v1/accommodations/**
        - id: reservation-management-service
          uri: lb://RESERVATION-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/reservations/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders: '*'
      default-filters:
        - name: AuthenticationFilter
          args:
            whitelist:
              - /api/v1/auth/**
              - /api/v1/accommodations/*
              - /api/v1/accommodations/user/*
              - /api/v1/reservations/accommodation/*/occupied-periods

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
