package com.onesquad.adapter.mapper;

import com.onesquad.adapter.dto.UserCreateDTO;
import com.onesquad.adapter.dto.UserResponseDTO;
import fr.onesquad.domain.user.Email;
import fr.onesquad.domain.user.PhoneNumber;
import fr.onesquad.domain.user.Role;
import fr.onesquad.domain.user.User;


public class UserDTOMapper {

    public static User toDomain(UserCreateDTO dto) {
        return new User(
                null, // ID will be generated by the database
                new Email(dto.email()),
                new PhoneNumber(dto.phoneNumber()),
                dto.password(),
                dto.firstName(),
                dto.lastName(),
                Role.valueOf(dto.role())
        );
    }

    public static UserResponseDTO toDTO(User user) {
        return new UserResponseDTO(
                user.id(),
                user.email().value(),
                user.phoneNumber().value(),
                user.firstName(),
                user.lastName(),
                user.role().name()
        );
    }
}
